// Copyright (c) 2026 Joseph Potashnik. Submitted for peer review to JMLR. Do not distribute or use without permission.
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace EarleyParserForGreedyGrammarInduction
{
    /// <summary>
    /// This class implements the Earley Set (interchangeable with the term Earley Column). It represents a single
    /// column in the Parser Chart, corresponding to a certain input index.
    /// 
    /// The class encapsulates the following:
    /// (i) Dictionaries:
    ///     Predecessors dictionary, holding all noncompleted Items. Predicted dictionary is a subset of Predecessors, indexed by LHS key.
    ///     Reductors dictionary, holding all completed Items in present or further Columns with a given key/span. 
    /// The two above dictionaries make Spontaneous Dot Shift trivial. Please see Finite Difference Paper for discussion.
    /// 
    /// (ii) Agendas for traversing actionable Items/States.
    ///     ActionableCompleteStates for completed states, and ActionableNonTerminalsToPredict for predicted states.
    ///     ActionableDeletedStates for uncompleted states, and NonTerminalsCandidatesToUnpredict for unpredicted states.
    ///     
    /// (iii) Data structures to keep track of last reparse(s) actions.
    ///       Reparses can be either accepted or rejected. These data Structures are used to revert or affirm the changes.
    ///     
    ///  EarleyColumn implements 
    ///  AddState - decides how to handle the added State/Item 
    ///         If it not completed, add to predecessor dictionary,
    ///         Otherwise, push to the completed States Agenda (in order to preserve BFS order over the parse forest).

    /// </summary>
    public class EarleyColumn
    {
        //Input index in the chart
        internal int Index { get; }
        //the lexical token associated with the Column/Set.
        internal string Token { get; set; }

        //(i) Dictionaries
        // Array-based predecessors for O(1) lookup
        internal List<EarleyState>[] PredecessorsBySymbol;

        // Track which array indices are actually used (for fast Reset)
        private readonly List<int> _usedPredecessorIndices = new(16);

        internal EarleySpans Reductors { set; get; }

        //(ii) Agendas
        internal CompletedStatesHeap ActionableCompleteStates { get; set; }
        internal Queue<int> ActionableNonTerminalsToPredict { set; get; }
        internal int CompletedStateCount { get; private set; }

        private readonly EarleyStatePool _statePool;
        private readonly EarleySpanPool _spanPool;


        internal EarleyColumn(int index, string token, int sentenceLength, EarleyStatePool statePool, EarleySpanPool spanPool)
        {
            Index = index;
            Token = token;
            //completed agenda is ordered in decreasing order of start indices (see Stolcke 1995 about completion priority queue).
            ActionableCompleteStates = new CompletedStatesHeap();
            ActionableNonTerminalsToPredict = new Queue<int>();

            // Initialize array-based predecessors
            int maxSymbolId = SymbolTable.Instance.Count;
            PredecessorsBySymbol = new List<EarleyState>[maxSymbolId];

            Reductors = new EarleySpans(sentenceLength, index);
            _statePool = statePool;
            _spanPool = spanPool;

            //We assume Epsilon Free grammars (apart from the empty string generated by  START -> epsilon rule).
            //However, this Earley Parser does support Epsilon productions easily.
            //if needed, uncomment the following.
            //CreateEpsilonState();
        }

        public void Reset()
        {
            // Clear only used predecessors (much faster than iterating entire array)
            for (int i = 0; i < _usedPredecessorIndices.Count; i++)
            {
                int index = _usedPredecessorIndices[i];
                var predecessorList = PredecessorsBySymbol[index];
                foreach (var state in predecessorList)
                {
                    _statePool.Return(state);
                }
                // Set to null so next parse will create fresh lists
                PredecessorsBySymbol[index] = null;
            }
            _usedPredecessorIndices.Clear();

            Reductors.Clear(_spanPool, _statePool);
            ActionableCompleteStates.Reset(_statePool);
            ActionableNonTerminalsToPredict.Clear();

            CompletedStateCount = 0;
        }

        private void CreateEpsilonState()
        {
            var epsilonId = SymbolTable.Instance.GetId(Grammar.EpsilonSymbol);
            var epsilonRule = new Rule(epsilonId, Array.Empty<int>());
            var epsilonCompletedState = _statePool.Rent(epsilonRule, 1, this);
            epsilonCompletedState.EndColumn = this;
            Reductors.AddState(epsilonCompletedState, _spanPool);
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal void AddState(EarleyState newState, Grammar grammar)
        {
            newState.EndColumn = this;

            if (newState.DotIndex < newState.Rule.RightHandSide.Length)
            {
                AddIncompleteState(newState, grammar);
            }
            else
            {
                AddCompletedState(newState);
            }
        }

        /// <summary>
        /// Specialized path for incomplete states (dot not at end of rule).
        /// Handles predecessor tracking, prediction, and spontaneous dot shift.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void AddIncompleteState(EarleyState newState, Grammar grammar)
        {
            var term = newState.Rule.RightHandSide[newState.DotIndex];

            // Get or create predecessors list (array-based lookup)
            var predecessors = PredecessorsBySymbol[term];
            if (predecessors == null)
            {
                predecessors = new List<EarleyState>(4);
                PredecessorsBySymbol[term] = predecessors;
                _usedPredecessorIndices.Add(term);

                // First time seeing this term - check if we need to predict
                if (grammar.RulesByLHS[term] != null)
                {
                    ActionableNonTerminalsToPredict.Enqueue(term);
                }
            }

            predecessors.Add(newState);

            // Perform spontaneous dot shift if reductors exist for this term
            if (Reductors.TryGetValue(term, out var reductorsWithSpans))
            {
                reductorsWithSpans.SpontaneousDotShift(newState, grammar, _statePool);
            }
        }

        /// <summary>
        /// Specialized path for completed states (dot at end of rule).
        /// Simply enqueues to the completion heap.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void AddCompletedState(EarleyState newState)
        {
            CompletedStateCount++;
            ActionableCompleteStates.Enqueue(newState);
        }
    }
}
