// Copyright (c) 2026 Joseph Potashnik. Submitted for peer review to JMLR. Do not distribute or use without permission.
using System.Collections.Generic;

namespace EarleyParserForGreedyGrammarInduction
{
    /// <summary>
    /// This class inherits from the Earley Parser.
    /// instead of being run as a parser, it runs as a generator, i.e, it generates the entire parse forest of the grammar, 
    /// i.e, the generator chart contains every tree generated by the grammar (up to a given sentence length). 
    /// </summary>
    public class EarleyGenerator : EarleyParser
    {
        public EarleyGenerator(Grammar g, Lexicon v, int maxWords)
            : base(g, v, System.Array.Empty<string>(), maxWords)
        { }

        protected override EarleyColumn[] PrepareEarleyTable(string[] _, int maxWords)
        {
            var sentenceLength = maxWords;
            var table = new EarleyColumn[sentenceLength + 1];
            for (var i = 1; i < table.Length; i++)
            {
                table[i] = new EarleyColumn(i, "generator", sentenceLength, _statePool, _spanPool);
            }

            table[0] = new EarleyColumn(0, "", sentenceLength, _statePool, _spanPool);
            return table;
        }

        protected override HashSet<int> GetPossibleSyntacticCategoriesForToken(string _)
        {

            return new HashSet<int>(_lexicon.POSWithPossibleWords.Keys);
        }

        public string[][] GetAllSequences(bool onlyPartsOfSpeechSequences = true)
        {
            var allNonTerminalsSequences = new string[_table.Length][];
            for (int i = 0; i < _table.Length; i++)
            {
                allNonTerminalsSequences[_table.Length - 1 - i] = GetFormattedString(i, onlyPartsOfSpeechSequences);
            }

            return allNonTerminalsSequences;
        }

    }
}
